server.name: kibana
server.host: "0"
elasticsearch.url: http://search-civicinsights-43tolpkrd5cmuxgsmetrh33ske.us-west-2.es.amazonaws.com:80 #http://elasticsearch:9200

## Disable X-Pack
## see https://www.elastic.co/guide/en/x-pack/current/xpack-settings.html
##     https://www.elastic.co/guide/en/x-pack/current/installing-xpack.html#xpack-enabling
#
xpack.security.enabled: false
xpack.monitoring.enabled: false
xpack.graph.enabled: false
xpack.reporting.enabled: false
